# Generated by Django 3.0.8 on 2020-07-26 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=1000)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=1000)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('super_cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.SuperCat')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recevie_name', models.CharField(max_length=255)),
                ('recevie_address', models.CharField(max_length=255)),
                ('recevie_tel', models.CharField(max_length=255)),
                ('remark', models.CharField(max_length=255)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('original_price', models.IntegerField()),
                ('current_price', models.IntegerField()),
                ('picture', models.CharField(max_length=255)),
                ('introduction', models.CharField(max_length=255)),
                ('views_count', models.IntegerField(verbose_name=0)),
                ('is_sale', models.BooleanField()),
                ('is_new', models.BooleanField()),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('subcat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.SubCat')),
                ('supercat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.SuperCat')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name=0)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('subcat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Goods')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
