# Generated by Django 3.0.8 on 2020-07-26 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name=0)),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Goods')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Orders')),
            ],
        ),
    ]
